#!/bin/bash

# Make sure you are root before doing anything
uid="$(id -u)"
if [ "$uid" -ne 0 ]; then
	echo "This script must be run using sudo!"
	exit 1
fi

# Save the original argument array since we modify it
original_args=("$@")

cd "$(dirname "$0")" || exit 255

echo "Getting started..."

# Source the generic function libraries that are also used by the product after
# setup. These functions are intended to be reusable outside of the setup process.
#source ../salt/common/tools/sbin/so-common
#source ../salt/common/tools/sbin/so-image-common

# Setup bash functionality is divided into functions and user-facing prompts. 
# Do not attempt to re-use any of this functionality outside of setup. Instead, 
# if needed, migrated generic functions into so-common.
source ./licenta-functions
source ./licenta-whiptail

# Finally, source the default variable definitions, which require availability of
# functions sourced above.
source ./licenta-variables

#intrebam daca utilizatorul este sigur ca vrea sa instaleze aplicatia
if (whiptail_you_sure); then
	true
else
	echo "Ati anulat Setup-ul." | tee -a "$setup_log"
	whiptail_cancel
fi

detect_os 

parse_install_username

progress() {
	local msg=${1:-'Asteptati instalarea...'}

	whiptail --title "$whiptail_title" --gauge "$msg" 6 70 0 # append to text
	
}

##procesul de instalare
setup_proc="$$"
#preflight check
percentage=0
{
	installer_progress_loop 'verificam daca pachetele necesare sunt instalate...' & # Run progress bar to 98 in ~8 minutes while waiting for package installs
	progress_bg_proc=$!
	installer_prereq_packages
	install_success=$?
	kill -9 "$progress_bg_proc"
	wait "$progress_bg_proc" &> /dev/null # Kill just sends signal, redirect output of wait to catch stdout
	if [[ $install_success -gt 0 ]]; then
		echo "Could not install packages required for setup, exiting now." >> "$setup_log" 2>&1
		kill -SIGUSR1 "$setup_proc"; exit 1
	fi
} | progress '...'


whiptail_enable_components
whiptail_choose_database
collect_webuser_inputs


# Begin install
{
	# Set initial percentage to 0
	export percentage=0

	# Show initial progress message
	set_progress_str 0 'Running initial configuration steps'

	
} | progress
